## Setting up

In [70]:
from numpy import (
    pi,inf,linspace,zeros,arange,sin,cos,tan,exp,maximum,abs,
    dot, set_printoptions
    )
set_printoptions(linewidth=500)
from numpy.linalg import norm, matrix_power, eigvals
from scipy.linalg import toeplitz

from matplotlib.style import use
use("seaborn")

from pltconfig import *

# Problem 0

## Part B

In [71]:
class q0b(object):
    
    def __init__(self, N=2):
        
        # check for even
        assert (N % 2 == 0), "N needs to be even"
        
        self.N = N
        
        self.D = self.calc_D()
        self.D2 = self.calc_D2()
        
        self.D_spectrum = eigvals(self.D)
        self.D_spectral_rad = self.D_spectrum.__abs__().max()
        
    def calc_D(self):
        
        N = self.N
        h = 2*pi/self.N
        x = h*arange(1,N+1)
        col = zeros(N)
        
        col[0] = 0.0
        col[1:] = 0.5*((-1.0)**arange(1,N))/tan(arange(1,N)*h/2.0)
        
        row = zeros(N)
        row[0] = col[0]
        row[1:] = col[N-1:0:-1]
        
        return toeplitz(col,row)
    
    def calc_D2(self):
        
        N = self.N
        h = 2*pi/self.N
        x = h*arange(1,N+1)
        col = zeros(N)
        
        col[0] = -((1./6)+((pi**2)/(3*h*h)))
        col[1:] = 0.5*((-1.0)**arange(1,N))/(sin(arange(1,N)*h/2.0)**2)
        
        row = zeros(N)
        row[0] = col[0]
        row[1:] = col[N-1:0:-1]
        
        return toeplitz(col,row)

Creating the object for N=2

In [72]:
N2 = q0b(N=2)

Showing the matrix $D_{N=2}$

In [73]:
N2.D

array([[ 0.000000e+00, -3.061617e-17],
       [-3.061617e-17,  0.000000e+00]])

Computing the square of the matrix $D_{N=2}^{2}$

In [74]:
matrix_power(N2.D,2)

array([[9.37349864e-34, 0.00000000e+00],
       [0.00000000e+00, 9.37349864e-34]])

In [75]:
N2.D2

array([[-0.5, -0.5],
       [-0.5, -0.5]])

The spectrum of the differentiation matrix is:

In [76]:
N2.D_spectrum

array([-3.061617e-17,  3.061617e-17])

The spectral radius of the differentiation matrix is:

In [77]:
N2.D_spectral_rad

3.061616997868383e-17

Creating the object for N=4

In [78]:
N4 = q0b(N=4)

Showing the matrix $D_{N=4}$

In [79]:
N4.D

array([[ 0.000000e+00,  5.000000e-01,  3.061617e-17, -5.000000e-01],
       [-5.000000e-01,  0.000000e+00,  5.000000e-01,  3.061617e-17],
       [ 3.061617e-17, -5.000000e-01,  0.000000e+00,  5.000000e-01],
       [ 5.000000e-01,  3.061617e-17, -5.000000e-01,  0.000000e+00]])

Computing the square of the matrix $D_{N=4}^{2}$

In [80]:
matrix_power(N4.D,2)

array([[-5.000000e-01, -3.061617e-17,  5.000000e-01,  3.061617e-17],
       [ 3.061617e-17, -5.000000e-01, -3.061617e-17,  5.000000e-01],
       [ 5.000000e-01,  3.061617e-17, -5.000000e-01, -3.061617e-17],
       [-3.061617e-17,  5.000000e-01,  3.061617e-17, -5.000000e-01]])

Looking at the second derivative matrix using the formulas derived

In [81]:
N4.D2

array([[-1.5, -1. ,  0.5, -1. ],
       [-1. , -1.5, -1. ,  0.5],
       [ 0.5, -1. , -1.5, -1. ],
       [-1. ,  0.5, -1. , -1.5]])

We observe that, indeed, for even powers, $D_{N=4}^{2}\neq D_{N=4}^{(2)}$

Computing the spectrum of the derivative matrix gives:

In [82]:
N4.D_spectrum

array([-3.06161700e-17+1.j, -3.06161700e-17-1.j,  2.12984716e-16+0.j, -1.51752377e-16+0.j])

Computing the spectral radius of the differentiation matrix for this case:

In [83]:
N4.D_spectral_rad

1.0

## Part C

In [84]:
class q0c(object):
    
    def __init__(self, N=3):
        
        assert (N % 2 == 1), "N needs to be odd"
        
        self.N = N
        
        self.D = self.calc_D()
        self.D2 = self.calc_D2()
        
        self.D_spectrum = eigvals(self.D)
        self.D_spectral_rad = self.D_spectrum.__abs__().max()
        
    def calc_D(self):
        
        N = self.N
        h = 2*pi/self.N
        x = h*arange(1,N+1)
        col = zeros(N)
        
        col[0] = 0.0
        col[1:] = 0.5*(-1.0)**arange(1,N)/sin(arange(1,N)*h/2.0)
        
        row = zeros(N)
        row[0] = col[0]
        row[1:] = col[N-1:0:-1]
        
        return toeplitz(col,row)
    
    def calc_D2(self):
        
        N = self.N
        h = 2*pi/self.N
        x = h*arange(1,N+1)
        col = zeros(N)
        
        col[0] = ((1./12)-((pi**2)/(3*h*h)))
        col[1:] = -0.5*((-1.0)**arange(1,N))*cos(arange(1,N)*h/2.0)/(sin(arange(1,N)*h/2.0)**2)
        
        row = zeros(N)
        row[0] = col[0]
        row[1:] = col[N-1:0:-1]
        
        return toeplitz(col,row)

Creating the object for $N=3$

In [85]:
N3 = q0c(N=3)

Looking at the differentiation matrix 

In [86]:
N3.D

array([[ 0.        ,  0.57735027, -0.57735027],
       [-0.57735027,  0.        ,  0.57735027],
       [ 0.57735027, -0.57735027,  0.        ]])

Taking the square of this matrix

In [87]:
matrix_power(N3.D, 2)

array([[-0.66666667,  0.33333333,  0.33333333],
       [ 0.33333333, -0.66666667,  0.33333333],
       [ 0.33333333,  0.33333333, -0.66666667]])

Looking at the second derivative matrix derived from the formulas

In [88]:
N3.D2

array([[-0.66666667,  0.33333333,  0.33333333],
       [ 0.33333333, -0.66666667,  0.33333333],
       [ 0.33333333,  0.33333333, -0.66666667]])

We observe that, indeed, for odd N $D_{N}^{2} = D_{N}^{(2)}$

The spectrum for the differentiation matrix is 

In [89]:
N3.D_spectrum

array([ 1.52655666e-16+1.j,  1.52655666e-16-1.j, -2.43353038e-16+0.j])

Computing the spectral radius:

In [90]:
N3.D_spectral_rad

1.0000000000000002